service: tagapp-backend
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    S3_BUCKET: tagapp-videos
    USERS_TABLE: Users
    POSTS_TABLE: Posts
    COMMUNITIES_TABLE: Communities
    INBOX_TABLE: Inbox
    JWT_SECRET: ${env:TAGAPP_JWT_SECRET, 'dev-secret-change-me'}
    BEDROCK_INFERENCE_PROFILE_ARN: ${env:BEDROCK_INFERENCE_PROFILE_ARN, ''}
    BEDROCK_FOUNDATION_MODEL_ID: ${env:BEDROCK_FOUNDATION_MODEL_ID, 'twelvelabs.pegasus-1-2-v1:0'}
    BEDROCK_REGION: ${env:BEDROCK_REGION, 'us-west-2'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::tagapp-videos/*
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource:
            - arn:aws:bedrock:*:*:model/*
            - arn:aws:bedrock:*:*:inference-profile/*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
          Resource:
            - arn:aws:dynamodb:us-west-2:*:table/Users
            - arn:aws:dynamodb:us-west-2:*:table/Posts
            - arn:aws:dynamodb:us-west-2:*:table/Communities
            - arn:aws:dynamodb:us-west-2:*:table/Inbox
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
plugins: []
functions:
  presignUpload:
    handler: src/presign.handler
    events:
      - httpApi:
          path: /presign
          method: post
  createPost:
    handler: src/posts.create
    events:
      - httpApi:
          path: /posts
          method: post
  getAllPosts:
    handler: src/posts.getAll
    events:
      - httpApi:
          path: /posts
          method: get
  getCommunityFeed:
    handler: src/posts.getCommunityFeed
    events:
      - httpApi:
          path: /communities/{communityId}/posts
          method: get
  listCommunities:
    handler: src/communities.list
    events:
      - httpApi:
          path: /communities
          method: get
  getUser:
    handler: src/users.get
    events:
      - httpApi:
          path: /users/{userId}
          method: get
  getUserRank:
    handler: src/users.rank
    events:
      - httpApi:
          path: /users/{userId}/rank
          method: get
  updateUser:
    handler: src/users.update
    events:
      - httpApi:
          path: /users/{userId}
          method: put
  getInbox:
    handler: src/inbox.get
    events:
      - httpApi:
          path: /users/{userId}/inbox
          method: get
  getVideoUrl:
    handler: src/get-video-url.handler
    events:
      - httpApi:
          path: /video-url/{objectKey+}
          method: get
  getUserPosts:
    handler: src/posts.getUserPosts
    events:
      - httpApi:
          path: /users/{userId}/posts
          method: get
  register:
    handler: src/auth.register
    events:
      - httpApi:
          path: /auth/register
          method: post
  login:
    handler: src/auth.login
    events:
      - httpApi:
          path: /auth/login
          method: post
  likePost:
    handler: src/interactions.likePost
    events:
      - httpApi:
          path: /posts/{postId}/like
          method: post
  unlikePost:
    handler: src/interactions.unlikePost
    events:
      - httpApi:
          path: /posts/{postId}/like
          method: delete
  savePost:
    handler: src/interactions.savePost
    events:
      - httpApi:
          path: /posts/{postId}/save
          method: post
  unsavePost:
    handler: src/interactions.unsavePost
    events:
      - httpApi:
          path: /posts/{postId}/save
          method: delete
  addComment:
    handler: src/interactions.addComment
    events:
      - httpApi:
          path: /posts/{postId}/comments
          method: post
  verifyVideo:
    handler: verification_lambda/handler.lambda_handler
    runtime: python3.11
    events:
      - httpApi:
          path: /verify
          method: post
