name: tagapp_flutter
description: Tag — Flutter frontend prototype
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  http: ^0.13.6
  image_picker: ^1.0.7
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
