name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-channel: [ 'stable' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Flutter --version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./app_flutter

      - name: Run analyzer
        run: flutter analyze
        working-directory: ./app_flutter

      - name: Run tests
        run: flutter test --no-pub
        working-directory: ./app_flutter

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./app_flutter

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app_flutter/build/app/outputs/flutter-apk/app-release.apk
